### ISSUE TITLE
Software architecture

### ISSUE THREAD

**Issue by diegoferigo** [robotology-playground/wearables#1]
Issue #1! :tada: 

## General outline

Let's use this issue to outline the class hierarchy for this project. You can find here below my first draft, feel free to edit it (we now have versioned commits!)

```cpp
namespace wear { // Main namespace

    using Vector3 = std::array<double, 3>;
    using Quaternion = std::array<double, 4>;
    using SensorName = std::string;

    template <typename S>
    using SensorVector = std::vector<S>;

    template <typename S>
    using SensorPtr = std::shared_ptr<S>;

     // Main interface    
    class IWear;

    // Implementations
    class XSensSuit; // : public IWear
    class EmgSuit;   // : public IWear
    class FTShoe;    // : public IWear

    namespace sensor {

        class enum Type;

        // Main interface
        class ISensor;

        // Interfaces
        class IOrientation;   // 4D 
        class IAccelerometer; // 3D
        class IGyroscope;     // 3D
        class IMagnetometer;  // 3D
        class Force3D; // 3D
        class Torque3D; // 3D
        class ISkin;
        class IEmg;
        class ITemperature;
        class IVirtualLink;
        class IVirtualJoint;

        // Derived interfaces
        class IForceTorque;     // : public IForce3D, ITorque3D
        class IFreeBodyAcceleration; // : public IAccelerometer

    } // sensor
} // wear
```

Then, what will match yarp interfaces in `yarp::dev`, the implementation will implement also that interface. An example for the orientation:

```cpp
class wear::XSensSuit : public wear::IWear
                        , wear::sensor::IOrientation
                        ...
                        , yarp::dev::IOrientationSensors
```

## `IWear` classes

```cpp
class wear::IWear
{
    // Generic
    SensorPtr<wear::sensor::ISensor> getSensor(const wear::SensorName name);

    // Sensors
    SensorPtr<wear::sensor::IOrientation> getOrientationSensor(const SensorName name);
    SensorPtr<wear::sensor::IPosition> getPositionSensor(const SensorName name);
    SensorPtr<wear::sensor::IAccelerometer> getAccelerometerSensor(const SensorName name);
    SensorPtr<wear::sensor::IGyroscope> getGyroscopeSensor(const SensorName name);
    SensorPtr<wear::sensor::IMagnetometer> getMagnetometerSensor(const SensorName name);
    SensorPtr<wear::sensor::ILinear> getLinearSensor(const SensorName name);
    SensorPtr<wear::sensor::IAngular> getAngularSensor(const SensorName name);
    SensorPtr<wear::sensor::IForceTorque> getForceTorqueSensor(const SensorName name);
    SensorPtr<wear::sensor::ITorque> getTorque3DSensor(const SensorName name);
    SensorPtr<wear::sensor::IForce> getForce3DSensor(const SensorName name);
    SensorPtr<wear::sensor::ISkin> getSkinSensor(const SensorName name);
    SensorPtr<wear::sensor::IEmg> getEmgSensor(const SensorName name);
    SensorPtr<wear::sensor::ITemperature> getTemperatureSensor(const SensorName name);

    // Multiple sensors
    SensorVector<SensorPtr<wear::sensor::IOrientation>> getOrientationSensors();
    SensorVector<SensorPtr<wear::sensor::IPosition>> getPositionSensors();
    SensorVector<SensorPtr<wear::sensor::IAccelerometer>> getAccelerometerSensors();
    SensorVector<SensorPtr<wear::sensor::IGyroscope>> getGyroscopeSensors();
    SensorVector<SensorPtr<wear::sensor::IMagnetometer>> getMagnetometerSensors();
    SensorVector<SensorPtr<wear::sensor::ILinear>> getLinearSensors();
    SensorVector<SensorPtr<wear::sensor::IAngular>> getAngularSensors();
    SensorVector<SensorPtr<wear::sensor::IForceTorque>> getForceTorqueSensors();
    SensorVector<SensorPtr<wear::sensor::ITorque3D>> getTorque3DSensors();
    SensorVector<SensorPtr<wear::sensor::IForce3D>> getForces3DSensors();
    SensorVector<SensorPtr<wear::sensor::ISkin>> getSkinSensors();
    SensorVector<SensorPtr<wear::sensor::IEmg>> getEmgSensors();
    SensorVector<SensorPtr<wear::sensor::ITemperature>> getTemperatureSensors();
}
```

```cpp
class wear::FTShoes : public wear::IWear
                    , public wear::sensor::ITorque
                    , public wear::sensor::IOrientation
                    , public wear::sensor::IAccelerometer
                    , public wear::sensor::IGyroscope
                    , public wear::sensor::IMagnetometer
                    , public yarp::dev::IThreeAxisGyroscopes
                    , public yarp::dev::IThreeAxisLinearAccelerometers
                    , public yarp::dev::IThreeAxisMagnetometers
                    , public yarp::dev::IOrientationSensors
                    , public yarp::dev::ISixAxisForceTorqueSensors
                    , public yarp::dev::ITemperatureSensors
```

```cpp
// .h

class wear::XSensSuit : public wear::IWear
private:
    class Impl;
    std::unique_ptr<Impl> pImpl;
public:
    SensorPtr<wear::sensor::ISensor> getSensor(const wear::SensorName name) override;
    ...
}

// .cpp

wear::XSensSuit::Impl {
    std::vector<std::shared_ptr<XSPrivate::XsOrientation>> orientations;
}

SensorPtr<wear::sensor::ISensor> wear::XSensSuit::getSensor(const wear::SensorName name)
{
}

// Somewhere else

namespace XSPrivate {
    class XsOrientation : public wear::sensor::IOrientation
    {}
    class XsFreeBodyAcceleration : public wear::sensor::IFreeBodyAcceleration
    {}
    ....
}
```

## `ISensor` classes

```cpp
class wear::sensor::ISensor
{
protected:
    wear::Type m_type;
    wear::FrameName m_frameName;
    wear::SensorName m_sensorName;
}
```

```cpp
class wear::sensor::IVirtualLink : public wear::sensor::ISensor
{
public:
    using LinkName = std::string;

    bool getPose(wear::Vector3& position, wear::Quaternion& orientation);
    bool getVelocity(wear::Vector3& linear, wear::Vector3& angular);
    bool getAcceleration(wear::Vector3& linear, wear::Vector3& angular);

    bool getOrientation(); // TODO as above
    bool getPosition();
    bool getLinearVelocity();
    bool getLinearAcceleration();
    bool getAngularVelocity();
    bool getAngularAcceleration();

protected:
    LinkName m_name;
    
}
```

```cpp
class wear::sensor::IVirtualSphericalJoint : public wear::sensor::ISensor
{
public:
    using JointName = std::string;

    bool getRPY(wear::Vector3& rpy);
    bool getRoll(double& r) = 0;
    bool getPitch(double& p) = 0;
    bool getYaw(double& y) = 0;

protected:
    JointName m_name;
    // TODO: parent / child links?
}
```

```cpp
class wear::sensor::IForce3D : public wear::sensor::ISensor
{
   bool getForce3D(wear::Vector3& force);
   bool getFx(double& fx);
   bool getFy(double& fy);
   bool getFz(double& fz);
}
```

```cpp
class wear::sensor::ITorque3D : public wear::sensor::ISensor
{
   bool getTorque3D(wear::Vector3& torque)
   {
    torque = {getTx(), getTy(), getTz()}; // TODO: also for others
    }
   bool getTx(double& tx);
   bool getTy(double& ty);
   bool getTz(double& tz);
}
```

```cpp
class wear::sensor::IForceTorque : public wear::sensor::ISensor
                              , wear::sensor::IForce3D
                              , wear::sensor::ITorque3D
{
    bool getForceTorque(wear::Vector3& force3d, wear::Vector3& torque3d);
}
```

cc @lucaTagliapietra @claudia-lat

**Comment by diegoferigo** [comment]
Ping @traversaro. I noticed you already passed here, but not the situation is more stable. Do you have any comments on our choices?

**Comment by traversaro** [comment]
Ok in general. 

Some comments: 
 * `bool getTx(wear::DataType& tx);` not a big fan of `wear::DataType` in place of `double`, it quite  complicates the readability of the API 
* not a big fan of `Wrench` as a term, I think it is quite a robotics jargon that just complicates readability
and its precise meaning in screw theory does not match perfectly what we mean by force torque 
* I think `ITorque` can be confusing as people may associate Torque with "1D joint torques" instead of "3D torques".
* We need to agree on a precise definition for RPY, linear velocity, angular velocity, linear acceleration, angular acceleration, otherwise any integration will be a nightmare. 
* For input/output of vector passed by reference I think `std::span` as described in https://github.com/robotology/idyntree/issues/430 is the perfect solution, unfortunately it will not be available until C++20. Have you consider if it make sense to define `wear::Span` ?

**Comment by diegoferigo** [comment]
> bool getTx(wear::DataType& tx); not a big fan of wear::DataType in place of double, it quite complicates the readability of the API . Even if you want to be general, I think it make sense to use a more readable name such as T or NumericType.

This is an attempt of having a centralized place which allows reducing the bandwidth if it is necessary. However, I'm not sure how to deal with it in thrift. If it is not possible, reverting to double would be the best choice.

> We need to agree on a precise definition for RPY, linear velocity, angular velocity, linear acceleration, angular acceleration, otherwise any integration will be a nightmare.

Yes, it should be stated clearly in the documentation.

> For input/output of vector passed by reference (and simplify actual use of the API) I think std::span as described in robotology/idyntree#430 is the perfect solution, unfortunately it will not be available until C++20. Have you consider if it make sense to define wear::Span ?

I'd really like to use span since there are **a lot** of data going around in this application. I'm not sure at this early stage how to deal and which problem we might face using external libraries in public interface headers. Any pointers or recommendations? 

Let's talk f2f on Torque / Wrench.

**Comment by traversaro** [comment]
> I'd really like to use span since there are a lot of data going around in this application. I'm not sure at this early stage how to deal and which problem we might face using external libraries in public interface headers. Any pointers or recommendations?

I was just thinking of just copying some MIT-licensed implementation of the span class in wear, as you can see in https://github.com/robotology/idyntree/pull/434  in the actual logic in the span class is quite limited, and given that the class is already standardized I don't think there will be a lot of activity on that front.

**Comment by diegoferigo** [comment]
The outline of the `IWear` interface and its sensors has been fixed and it's quite stable already since few months. You can find it in the following resources. Closing this issue.

- [IWear.h](https://github.com/robotology-playground/wearables/blob/master/interfaces/IWear/include/Wearable/IWear/IWear.h)
- [ISensor.h](https://github.com/robotology-playground/wearables/blob/master/interfaces/IWear/include/Wearable/IWear/Sensors/ISensor.h)
- [Sensors](https://github.com/robotology-playground/wearables/tree/master/interfaces/IWear/include/Wearable/IWear/Sensors)
