### ISSUE TITLE
Develop XsensMVNControl Wrapper / Remote

### ISSUE THREAD

**Issue by diegoferigo** [robotology-playground/wearables#10]
This class allows controlling the `XsensMVNDriver` from non-local (even non-Windows) machines.

It should:

- Implement an interface for the controls (calibrating, start / stop acquisition) through RPC calls

**Comment by lrapetti** [comment]
`XsensMVNControlWrapper` has been developed (https://github.com/robotology-playground/wearables/blob/master/wrappers/IXsensMVNControl/src/IXsensMVNControlWrapper.cpp). 
@diegoferigo @Yeshasvitvs if you agree, we can close this issue.

**Comment by diegoferigo** [comment]
Yes, closing.
