### ISSUE TITLE
Discuss removing the IWearRemapper message

### ISSUE THREAD

**Issue by lrapetti** [robotology-playground/wearables#29]
The main purpose of the `IWearRemapper` is to expose the `IWear` interface, but it also exposes the `IWear` as a message in a port.

As discussed in https://github.com/robotology-playground/wearables/issues/27#issuecomment-467059753, this latter function may be removed and an `IWearWrapper` may be used instead.

**Comment by lrapetti** [comment]
cc @diegoferigo

**Comment by DanielePucci** [comment]
We talked f2f with @diegoferigo  and he agrees. Please, @lrapetti  handle this removal.

**Comment by lrapetti** [comment]
PR opened in https://github.com/robotology-playground/wearables/pull/34
