### ISSUE TITLE
Develop the new XsensMVNDriver class

### ISSUE THREAD

**Issue by diegoferigo** [robotology-playground/wearables#3]
This class will replace the former [robotology-playground/xsens-mvn/xsensdriver](https://github.com/robotology-playground/xsens-mvn/tree/master/xsensdriver).

Features:

- Support of the Xsens 2018.0.3 SDK
- YARP independent
- C++14
- Works only in Windows (due to Xsens' SDK)

**Comment by lrapetti** [comment]
`XsensMVNDriver` has been developed (https://github.com/robotology-playground/wearables/tree/feature/cleanup/XSensMVN). 
@diegoferigo if you agree, we can close this issue.

**Comment by traversaro** [comment]
I typically find more convenient to close issues when the relevant features has landed in `master` or `devel`, but I guess it is up to the maintainer to decide the policy on this.

**Comment by lrapetti** [comment]
> I typically find more convenient to close issues when the relevant features has landed in `master` or `devel`, but I guess it is up to the maintainer to decide the policy on this.

I was pointing to a branch, but the same feature is also supported in the `master` (https://github.com/robotology-playground/wearables/tree/master/XSensMVN).

**Comment by traversaro** [comment]
Great!

**Comment by diegoferigo** [comment]
Yes, closing.

**Comment by diegoferigo** [comment]
One missing thing is exposing the virtual points, as discussed with @claudia-lat. We will discuss it in a separate issue when we will need this feature and start the development.
