### ISSUE TITLE
Add a wiki on how to add and implement new sensors

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology-playground/wearables#33]
In this issue, we track the details on How to add a new wearable sensor and implement the methods. 

@diegoferigo @lrapetti

**Comment by Yeshasvitvs** [comment]
An initial draft of the wiki is [added](https://github.com/robotology-playground/wearables/wiki/Adding-and-Implementing-New-Sensors). @diegoferigo @lrapetti please try to review and let me know if it is ok for the time being. We can close this issue accordingly.

**Comment by diegoferigo** [comment]
Looks good to me! Thanks for writing it down :)

**Comment by Yeshasvitvs** [comment]
@diegoferigo we can close this issue right ?

**Comment by diegoferigo** [comment]
Yes, go ahead.
