### ISSUE TITLE
Develop a thrift file for serializing data of the IWear interface

### ISSUE THREAD

**Issue by diegoferigo** [robotology-playground/wearables#4]
This thrift autogenerates the code for serializing the data contained into an `IWear` object.

**Comment by lrapetti** [comment]
`WearableData.thrift` has been developed (https://github.com/robotology-playground/wearables/blob/feature/cleanup/msgs/thrift/WearableData.thrift). 
@diegoferigo @Yeshasvitvs if you agree, we can close this issue.

**Comment by diegoferigo** [comment]
Yes, closing
