### ISSUE TITLE
Develop a new WearDataToXsensFrameWrapper class

### ISSUE THREAD

**Issue by diegoferigo** [robotology-playground/wearables#5]
This class implements a YARP wrapper that reads from a yarp port a message generated with the new thrift file (#4) and writes to another yarp port the same message with the former serialization [`XsensFrame.thrift`](https://github.com/robotology-playground/xsens-mvn/tree/master/msgs/thrift/XsensFrame.thrift).

**Comment by claudia-lat** [comment]
We can close this issue since it has been opened for the back compatibility to use HDE before the refactoring.
