### ISSUE TITLE
Develop XsensSuit

### ISSUE THREAD

**Issue by diegoferigo** [robotology-playground/wearables#6]
This new class is one of the implementations of the `IWear` interface. This new `XsensSuit` class wraps the standalone `XsensMVNDriver` with a `yarp::dev::DeviceDriver`.

It will:

- Contain the loop for gathering data from the driver
- Implement the `IWear` interface
- Implement an interface for controlling the driver (calibration, start / stop acquisition, ...)

**Comment by lrapetti** [comment]
`XsensSuit` has been developed (https://github.com/robotology-playground/wearables/tree/master/devices/XsensSuit). 
@diegoferigo @Yeshasvitvs if you agree, we can close this issue.

**Comment by diegoferigo** [comment]
Yes, closing.
